### ISSUE TITLE
Reorder execution of `setup.sh`

### ISSUE THREAD

**Issue by dlavoieb** [mcgill-robotics/compsys#23]
We noticed one problem with the installation order. 

Assuming a clean ubuntu install, the repo's `setup.sh` script is executed after cloning, when ROS is not yet installed. 

If we want to use the `setup.sh` script to install robot specific packages (primarly ROS packages) this is not going to work. Is there a way to reorder the install steps such that the script is executed after ros is installed?

**Comment by anassinator** [comment]
That was already fixed a couple of weeks ago
