### ISSUE TITLE
Set up process may not exit on the first error

### ISSUE THREAD

**Issue by foochuanwei** [mcgill-robotics/compsys#34]
Something to be aware of. At present, compsys will happily continue the set up process even when the installation of apt, gem, pip and pip3 dependencies fail, or when the ROS key import fails.

This is not good because a normal user will not bother reading the entire output and will assume that "All done!" means that everything is set up correctly.

`set -e` is present in the install script, but that line only applies to the install script itself and not to the scripts executed in the shells that the install script starts (e.g. `./setup/ros/install`).

**Comment by Baycken** [comment]
So I tested the main installer script and `set -e` does affect the script executed in the shells that install script starts.

Testing procedure:
1. Created executable `test1` and `test2`
    - test1:
        ```
        #!/binbash
        ./test2
        ```
    - test2:
        ```
        #!/binbash
        exit 1
        ```
2. Added `./test1` in the main install immediately after `set -e`
3. Run main installer

And installer exited as expect and no code after `./test1` was run.

**Comment by foochuanwei** [comment]
@Baycken It seems that the rules for `set -e` are not straightforward.

* test1:
```
#!/bin/bash
set -e
./test2
echo 'At the end of test1'
```

* test2:
```
#!/bin/bash
please-do-my-homework  # Bad command (exit code 127).
pip3 install auto-homework  # Bad command (exit code 1).
echo 'At the end of test2'
```

Run: `./test1`
Result: `./test1` does not exit as expected.

**Comment by Baycken** [comment]
Hmm, I guess I didn't test enough. But once `set -e` is added to `test2`, it worked as expected.
As I added `set -e` for all the scripts so it should be fine.
