### ISSUE TITLE
Document non-default tmux key bindings in README.md

### ISSUE THREAD

**Issue by foochuanwei** [mcgill-robotics/compsys#44]
Document [this line](https://github.com/mcgill-robotics/compsys/blob/master/setup/config/tmux.conf#L3) in README.md because a user new to tmux will likely be following guides that use the default `Ctrl-b` instead of our `Ctrl-a`.

Also document the key bindings for screen splitting. We should probably not unbind the defaults.

**Comment by anassinator** [comment]
The bindings we use are common bindings people use because the defaults are retarded, but I agree with you nonetheless.

**Comment by Baycken** [comment]
@anassinator Could we close this already?
