### ISSUE TITLE
Revise README and FAQ and update accordingly

### ISSUE THREAD

**Issue by malcolmwhat** [mcgill-robotics/compsys#6]
@anassinator There are some things that look out of date in the Readme, when you have time please revise it.

**Comment by anassinator** [comment]
Sure! Could you list those things to make sure I don't miss any?

**Comment by malcolmwhat** [comment]
Yeah the only thing that got me was the FAQ section: 'which project am I working on' could use some revision. Also I can't see it properly, but considering your recent commits the 'what will my shell look like' might be outdated.

Sent from my iPhone

On 18 Oct 2015, at 23:54, "Anass Al" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure! Could you list those things to make sure I don't miss any?

-

**Comment by anassinator** [comment]
The "What will my shell look like?" had already been updated to reflect those changes, but I've revised everything else in 2082f36.
