### ISSUE TITLE
pushd into current directory cause popd to fail

### ISSUE THREAD

**Issue by Baycken** [mcgill-robotics/compsys#74]
If you pushd into the current directory, the command will exit successfully but without putting the current directory into the stack, causing the subsequent popd to fail either because a stack mismatch, or because the stack is empty.

This cause `rosworkon drone gsg` in `drone/catkin_ws` to exit with exit code.

Test case 1:
- Open new terminal.
- Run `pushd ~/`
- Run `popd`
- failed with `popd: directory stack empty`

Test case 2:
- Open new terminal.
- Run `cd /`
- Run `pushd ~/`
- Run `pushd ~/`
- Run `popd`, this should `cd` to `~/` and pop the stack to `/`, but it `cd` to `/` instead and stack is now empty.
- Run `popd` again, stack is empty so command failed with `popd: directory stack empty`

**Comment by Baycken** [comment]
I this this is a bug on bash, just opened an issue on gnu, will see what they say.

but for the time being, we can add to be beginning of the script:
```
if [[ $(pwd) -ne ${HOME} ]]; then
  pushd ${HOME}
  pushd_home='true'
fi
```

And make sure that the immediate next pushd will never be to `${HOME}`

Then add at the end of the script:
```
if [[ ${pushd_home} ]]; then
  popd
fi
```

**Comment by anassinator** [comment]
why is this specific to the home directory?

**Comment by Baycken** [comment]
Not specific to home, just give that as an example

**Comment by foochuanwei** [comment]
@Baycken Did you use `bash` or `zsh` in your tests?
Everything works as expected in bash.
