### ISSUE TITLE
rosrun autocompletion is broken for zsh

### ISSUE THREAD

**Issue by Baycken** [mcgill-robotics/compsys#76]
rosrun autocompletion is broken for zsh only. bash still works fine.

**Comment by foochuanwei** [comment]
Guesswork: 
You may be looking for [`bashcompinit`](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Use-of-compinit).

**Comment by anassinator** [comment]
Unable to reproduce.
Does this fix it? https://github.com/mcgill-robotics/compsys/blob/2082f36c100e132d4c91e7f90cd69df6788e3d5c/README.md#6-i-installed-zsh-why-does-rosrun-autocompletion-not-work
