### ISSUE TITLE
Simpler pip install

### ISSUE THREAD

**Issue by foochuanwei** [mcgill-robotics/compsys#83]
What is the motivation for writing `get_dependencies pip3 | xargs sudo -H pip3 install --upgrade || :` ([reference](https://github.com/mcgill-robotics/compsys/blob/1c3246f1caf24c2f78c83e282b8d23d4e3bb10cf/update#L28)) instead of something like `sudo pip3 install --upgrade --requirement packages/pip3`?

**Comment by anassinator** [comment]
As long as it ignores failures and we keep the `-H`, it will behave the same way and the answer would be there's no good reason 😛

**Comment by foochuanwei** [comment]
In that case, it should be replaced with something like `sudo -H pip3 install --upgrade --requirement packages/pip3 || :` because that will allow comments inside the requirements file.

**Comment by anassinator** [comment]
I wouldn't expect that too work. Does it?

**Comment by foochuanwei** [comment]
test:
```
#!/bin/bash

sudo -H pip3 install --upgrade --requirement packages/pip3 || :
```

packages/pip3:
```
PyYAML
kA&*%*9
requests
```

`./test`
Looks ok.

**Comment by anassinator** [comment]
ok then. you can "fix" this :P
